### ISSUE TITLE
Request of Apache packages

### ISSUE THREAD

**Issue by javigomez** [travis-ci/apt-source-whitelist#16]
Hi,

I'm using this script in the travis legacy infraestructure:

```yaml
php:
- 5.4
before_script:
- phpenv config-add .travis.ini
- phpenv rehash
# Following line uses a bot account to authenticate in github and make composer stable and faster, see https://redweb.atlassian.net/wiki/pages/viewpage.action?pageId=46694753
- composer config -g github-oauth.github.com 4d92f9b609
- composer install --prefer-dist
# Install Apache
- sudo apt-get update -qq
- sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl php5-gd > /dev/null
- sudo /etc/init.d/apache2 stop
- sudo sed -i -e "s,APACHE_RUN_USER=www-data,APACHE_RUN_USER=$USER,g" /etc/apache2/envvars
- sudo sed -i -e "s,APACHE_RUN_GROUP=www-data,APACHE_RUN_GROUP=$USER,g" /etc/apache2/envvars
- sudo chown -R $USER /var/lock/apache2
- sudo chown -R $USER:$USER /var/www
- ln -s $TRAVIS_BUILD_DIR/tests/ /var/www/tests
- sudo sed -i -e "s,AllowOverride[ ]None,AllowOverride All,g" /etc/apache2/sites-available/default
- sudo /etc/init.d/apache2 start
# XVFB
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
# Window manager
- "sudo apt-get install fluxbox -y --force-yes"
- "fluxbox &"
- sleep 3 # give fluxbox sometime to start
```

The goal of it is to create an apache webserver in order to execute system tests against it.

I would like to request the following packages in the APT Addon(http://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages): apache2, libapache2-mod-php5, php5-curl, php5-mysql, php5-intl, php5-gd.

Also I would like to request if you can preconfigure this packages to have the right permissions in order I don't need to use Sudo to run a website in it.

Thanks very much.
