### ISSUE TITLE
APT source whitelist request for ppa:george-edison55/cmake-3.x

### ISSUE THREAD

**Issue by fire** [travis-ci/apt-source-whitelist#218]
Needed for cmake and cmake-data which are 3.x.

deb src ppa:george-edison55/cmake-3.x

See https://github.com/travis-ci/travis-ci/issues/4631

**Comment by techtonik** [comment]
Try https://launchpad.net/~george-edison55/+archive/ubuntu/precise-backports which is already there - https://github.com/travis-ci/apt-source-whitelist/commit/35ecc916f04c0074862209fdc7b033004c30bfc7

**Comment by elken** [comment]
Fails to install because `cmake-data` isn't backported.

**Comment by techtonik** [comment]
@elken are you sure? Add `cmake-data` explicitly.

**Comment by elken** [comment]
The fact that the package isn't actually in the PPA is what convinced me.

**Comment by techtonik** [comment]
@elken so? It might be a launchpad bug, or you looking at a wrong page. What was the response from apt-get`?

**Comment by elken** [comment]
Exactly as described, wrong cmake data. Can't force the version, it's not there.

**Comment by techtonik** [comment]
Post a link to your failing build on travis.

**Comment by elken** [comment]
There aren't any now because I gave up fighting them and moved to a 
superior platform in the form of Semaphore. Only have travis for OSX 
builds, but would be nice to have it do Linux too. Had the exact issue 
described here and in plenty of other issues.

**Comment by techtonik** [comment]
@elken here is the solution I've come up with for PySide:
```
language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - debian-sid
    packages:
    - cmake
    - cmake-data
    - qt5-default
script:
  - python setup.py install
```
https://github.com/techtonik/pyside2-setup/blob/56c6f931f1f37ac489aa3fb6a3f7e656ada632e4/.travis.yml
