### ISSUE TITLE
APT source whitelist request for dynamips

### ISSUE THREAD

**Issue by linickx** [travis-ci/apt-source-whitelist#223]
```
deb http://us.archive.ubuntu.com/ubuntu/ precise multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ precise multiverse
```

Hi, I have a personal [opensource project that configures Cisco routers](https://github.com/linickx/crassh). The project has a draft, initial [test that connects to a router, runs a command and then validates the output](https://github.com/linickx/crassh/commit/e4fee2b823b74fb946ed7a2376c15b031c1bfe16) to what is expected.

I would like to be able to run the test within travis-ci; this will require `dynamips` added to the whitelist to run the router emulation. 

To make the package usable, it will also require Setuid (`sudo chmod 4755 /usr/bin/dynamips`) and the ability to create a virtual interface; the virtual interface will connect the "ci server" to the emulated router, so something like `sudo ifconfig tap0 inet 1.1.1.1 net mask 255.255.255.252` would also need to be permitted for use in the `before_script` in a .travis.yml

Assuming that sudo will never be allowed and that the permissions of `dynamips` and `ifconfig` can somehow be fixed when the package is added to the whitelist?  Below is an example, anticipated rough draft of a  travil.yml file:

```
language: python

python:
  - "2.6"
  - "3.5"

addons:
  apt:
    packages:
    - dynamips

before_install:
# Get the router image from a server as it cannot be included within the opensource project
    - wget http://something.server/c3725-advsecurityk9-mz.124-25c.bin
    - wget http://something.server/r1.txt

install:
# install the python script, deps and start the virtual router 
  - pip install .
  - pip install paramiko
  - dynamips -s 0:0:tap:tap0 -P 3725 -T 2001 --idle-pc=0x607081e0 -C r1.txt c3725-advsecurityk9-mz.124-25c.bin &

before_script:
# configure our virtual interface and sleep 60, to give the router a minute to finish booting
    - ifconfig tap0 inet 1.1.1.1 netmask 255.255.255.252
    - sleep 60

script: py.test

branches:
  only:
      - tests
```
