### ISSUE TITLE
APT source whitelist request for multiverse

### ISSUE THREAD

**Issue by ax3l** [travis-ci/apt-source-whitelist#233]
Currently the only reason I need sudo on trusty is because `addons.apt.sources` does not allow `multiverse`.

```
multiverse
```

Example:
```
addons:
  sources:
    - multiverse
  apt:
    sources:
      - multiverse
    packages:
      - nvidia-cuda-toolkit
      - nvidia-cuda-dev
```

Related to the solution of #223
