### ISSUE TITLE
APT source whitelist request for llvm-toolchain-precise-3.9

### ISSUE THREAD

**Issue by nikkikom** [travis-ci/apt-source-whitelist#300]
deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.9 main
deb-src http://apt.llvm.org/precise/ llvm-toolchain-precise-3.9 main

**Comment by palmer-dabbelt** [comment]
I believe this GPG key is needed <http://llvm.org/apt/llvm-snapshot.gpg.key>.  At least, that's what the 3.8 version looks like: <https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json#L187>.

**Comment by cocreature** [comment]
Can we please get this whitelisted? LLVM 3.9 is supposed to be out next week so now is the time to test things to catch any lastminute bugs.

**Comment by cocreature** [comment]
LLVM-3.9 is now [released](http://lists.llvm.org/pipermail/llvm-dev/2016-September/104460.html), any way to accelerate getting this whitelisted?

**Comment by offa** [comment]
As a workaround until 3.9 becomes available:

```yml
      addons:
        apt:
          packages:
            - clang-3.9
            - libc++-dev
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
```
