### ISSUE TITLE
GPG error occurs with `debian-sid` alias

### ISSUE THREAD

**Issue by spluque** [travis-ci/apt-source-whitelist#417]
Using the following directive:

```yml
addons:
  apt:
    sources:
      - debian-sid
    update: true
    packages:
      - r-base
      - r-base-dev
```

There's a list of packages that cannot be authenticated (https://travis-ci.org/github/spluque/scikit-diveMove/jobs/704835048).  Any recommendations?
