### ISSUE TITLE
APT source whitelist request for Elasticsearch 1.6

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/apt-source-whitelist#46]
This replaces travis-ci/travis-ci#4265.

The original text by @saveriomiroddi follows

------

This repository contains the Elasticsearch v1.6 Debian repository, which is compatible with Ubuntu [verified on Trusty].

Deb source line: deb http://packages.elastic.co/elasticsearch/1.6/debian stable main
Key: https://packages.elastic.co/GPG-KEY-elasticsearch

**Comment by rbatta** [comment]
+1

**Comment by ZurabWeb** [comment]
ES 1.7.1 is released already: https://www.elastic.co/blog/elasticsearch-1-7-1-and-1-6-2-released. Tested, works with Ubuntu.

**Comment by BanzaiMan** [comment]
I've added `elasticsearch-1.6` and `elasticsearch-1.7`.

```yaml
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
```

Closing this now.
