### ISSUE TITLE
APT source whitelist request for qtbase5-dev and qbs

### ISSUE THREAD

**Issue by arhad** [travis-ci/apt-source-whitelist#93]
I use this gist to compile my Qt-based application on Travis CI using Qt Build System:

``` yaml
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - qtbase5-dev
    sources:
      - qbs
```

But the worker prints this error:

```
Adding APT Sources (BETA)
Disallowing sources: qbs
If you require these sources, please review the source approval process at: https://github.com/travis-ci/apt-source-whitelist#source-approval-process
Installing APT Packages (BETA)
Disallowing packages: qtbase5-dev
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```
